name: Hassfest

on:
  push:
    branches: [main]
  pull_request:

jobs:
  hassfest:
    name: Hassfest
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5

      - name: Hassfest validation
        uses: home-assistant/actions/hassfest@master
